on:
  rss:
    url: https://github.com/pinterf/xy-VSFilter/releases.atom
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:  |
            XySubFilter  pinterf VER. updated
            ${{on.rss.outputs.title}}
            ${{on.rss.outputs.contentSnippet}}
            Time: ${{on.rss.outputs.pubDate}}
            ${{on.rss.outputs.link}}
